[General]
ScreenWidth="2560"
ScreenHeight="1600"
ScreenPadding=""
Font="Open Sans"
FontSize="13"
KeyboardSize="0.4"
RoundCorners="20"
Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText=""

BackgroundPlaceholder="Backgrounds/violet-evergarden.png"
Background="Backgrounds/violet-evergarden.mp4"
BackgroundSpeed="1.0"
PauseBackground=""
DimBackground="0.08"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#2f2e2a"
DateTextColor="#2f2e2a"
TimeTextColor="#2f2e2a"
FormBackgroundColor="#2f2e2a"
BackgroundColor="#2f2e2a"
DimBackgroundColor="#2f2e2a"
LoginFieldBackgroundColor="#46443b"
PasswordFieldBackgroundColor="#46443b"
LoginFieldTextColor="#f9f1d3"
PasswordFieldTextColor="#f9f1d3"
UserIconColor="#cdbba4"
PasswordIconColor="#cdbba4"
PlaceholderTextColor="#aaa8a0"
WarningColor="#e99276"
LoginButtonTextColor="#2f2e2a"
LoginButtonBackgroundColor="#cdbba4"
SystemButtonsIconsColor="#f9f1d3"
SessionButtonTextColor="#f9f1d3"
VirtualKeyboardButtonTextColor="#f9f1d3"
DropdownTextColor="#2f2e2a"
DropdownSelectedBackgroundColor="#cdbba4"
DropdownBackgroundColor="#f9f1d3"
HighlightTextColor="#2f2e2a"
HighlightBackgroundColor="#cdbba4"
HighlightBorderColor="#aaa8a0"
HoverUserIconColor="#f9f1d3"
HoverPasswordIconColor="#f9f1d3"
HoverSystemButtonsIconsColor="#cdbba4"
HoverSessionButtonTextColor="#cdbba4"
HoverVirtualKeyboardButtonTextColor="#cdbba4"

PartialBlur="true"
FullBlur=""
BlurMax="8"
Blur="2.0"
HaveFormBackground="true"
FormPosition="left"

VirtualKeyboardPosition="left"

HideVirtualKeyboard="false"
HideSystemButtons="true"
HideLoginButton="false"
UseRealName="true"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
